language: python
python:
  - "3.6"
cache: pip
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - python -m pytest -s --cov-report term-missing --cov autovers -v
after_success:
  - coveralls
