version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            pip3 install -r requirements-test.txt
      - run:
          name: run tests
          command: |
            python3 -m pytest -s --cov-report term-missing --cov autovers -v --junitxml=test-results/junit.xml
      - store_test_results:
          path: test-results

      - store_artifacts:
          path: test-results
